name: Update CDIP SCCOOS Data

on:
  schedule:
    - cron: "*/15 * * * *" # Run every 15 minutes
  workflow_dispatch: # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Fetch CDIP Data
        run: |
          mkdir -p public/data
          curl -s https://cdip.ucsd.edu/data_access/sccoos.cdip | grep -A 1000 "<pre>" | grep -B 1000 "</pre>" | grep -v "<pre>" | grep -v "</pre>" > public/data/cdip_sccoos.txt

      - name: Check for changes
        id: verify_diff
        run: |
          git add -N public/data/cdip_sccoos.txt
          if ! git diff --exit-code --quiet public/data/cdip_sccoos.txt; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push if changed
        if: steps.verify_diff.outputs.changes_detected == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/data/cdip_sccoos.txt
          git commit -m "Update CDIP data"
          git push
